# Change these first
owner: 164-life # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Renekey
    url: https://renekey.blue
  - name: Renekey-Lite
    url: https://lite.renekey.blue
  - name: Renedon
    url: https://renedon.red

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.1641.ltd
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/147372151?s=512&v=4
  name: 1641-Status
  introTitle: "1641-Status"
  introMessage: 1641projectのStatusです。
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
